[dotfiles]
"~/.config/fish/config.fish"        = {}
"~/.config/ghostty/config"          = {}
"~/.config/aerospace/aerospace.toml" = {}
"~/.config/kitty/kitty.conf"        = {}

[bootstrap.packages]
"brew:openssl@3" = "latest"
"brew:readline" = "latest"
"brew:sqlite" = "latest"
"brew:asyncapi" = "latest"
"brew:cmake" = "latest"
"brew:curl" = "latest"
"brew:difftastic" = "latest"
"brew:libyaml" = "latest"
"brew:duckdb" = "latest"
"brew:ffmpeg" = "latest"
"brew:fish" = "latest"
"brew:fzf" = "latest"
"brew:gcc" = "latest"
"brew:gh" = "latest"
"brew:git" = "latest"
"brew:gnupg" = "latest"
"brew:herdr" = "latest"
"brew:hurl" = "latest"
"brew:imapsync" = "latest"
"brew:jj" = "latest"
"brew:jjui" = "latest"
"brew:k9s" = "latest"
"brew:libpq" = "latest"
"brew:mise" = "latest"
"brew:neovim" = "latest"
"brew:ossp-uuid" = "latest"
"brew:pkgconf" = "latest"
"brew:qemu" = "latest"
"brew:ripgrep" = "latest"
"brew:tmux" = "latest"
"brew:tree" = "latest"
"brew:watch" = "latest"
"brew:xpdf" = "latest"
"brew:zlib" = "latest"
"brew-cask:1password" = "latest"
"brew-cask:1password-cli" = "latest"
"brew-cask:nikitabobko/tap/aerospace" = "latest"
"brew-cask:balenaetcher" = "latest"
"brew-cask:betterdisplay" = "latest"
"brew-cask:brave-browser" = "latest"
"brew-cask:firefox" = "latest"
"brew-cask:font-jetbrains-mono" = "latest"
"brew-cask:font-open-sans" = "latest"
"brew-cask:ghostty" = "latest"
"brew-cask:kitty" = "latest"
"brew-cask:obsidian" = "latest"
"brew-cask:onlyoffice" = "latest"
"brew-cask:orbstack" = "latest"
"brew-cask:slack" = "latest"
"brew-cask:spotify" = "latest"
"brew-cask:syncthing-app" = "latest"
"brew-cask:tablepro" = "latest"
"brew-cask:tailscale-app" = "latest"
"brew-cask:transmission" = "latest"
"brew-cask:twingate" = "latest"
"brew-cask:utm" = "latest"
"brew-cask:vlc" = "latest"
"brew-cask:vscodium" = "latest"
