[user]
name = "crbelaus"
email = "cristian@crbelaus.com"

[ui]
editor = "nvim"
diff-editor = ":builtin"
default-command = "log"

[aliases]
blame = ["file", "annotate"]
untrack = ["file", "untrack"]
flog = ["log", "-r", "::@"]
